### ISSUE TITLE
Use test suite for tests?

### ISSUE THREAD

**Issue by Zegnat** [cleverdevil/microformats2#1]
How hard would it be to import [microformats/tests](https://github.com/microformats/tests) and run the schema against all of those example JSON outputs? Theoretically all of those are valid mf2 output, so all of them should pass. If any of them doesn’t pass, an issue can be filed either against the schema or against the test suite.

**Comment by cleverdevil** [comment]
This can now be done using the `validate_all.py` tool that I checked in today. If you have the microformats tests checked out, you can simply run:

```bash
python tools/validate_all.py ../mf2tests/tests/microformats-v2/
```

This will (currently) output the following:

```
F:  ../mf2tests/tests/microformats-v2/h-resume/education.json
F:  ../mf2tests/tests/microformats-v2/h-resume/work.json
F:  ../mf2tests/tests/microformats-v2/h-card/horghcard.json
F:  ../mf2tests/tests/microformats-v2/h-as-note/note.json
F:  ../mf2tests/tests/microformats-v2/h-news/minimum.json
F:  ../mf2tests/tests/microformats-v2/h-news/all.json
F:  ../mf2tests/tests/microformats-v2/h-org/simple.json
F:  ../mf2tests/tests/microformats-v2/h-org/hyperlink.json
F:  ../mf2tests/tests/microformats-v2/h-org/simpleproperties.json
Results
   Successes:  71
    Failures:  9
       Total:  80
```

This is mostly due to legacy and incorrect things in the tests themselves.
