### ISSUE TITLE
Make the schema available as JSON

### ISSUE THREAD

**Issue by grantcodes** [cleverdevil/microformats2#2]
I don't understand the intricacies of it, but is it possible to generate the actual schema as JSON and make that available?

That way people can use it in other languages

**Comment by cleverdevil** [comment]
Yeah it’s really easy to do. I’ll take care of it this weekend and post an update!

There is also a code snippet in the README that shows how to print out the schema, for now.

**Comment by cleverdevil** [comment]
Done in: 
https://github.com/cleverdevil/microformats2/commit/ed1e5efe04ec48d2be45855d9918485e13bc6c7b
